@startuml ipc05.1_design.png

participant "ChatExtension"
participant "CommServer2" <<singleton>>
participant "Message"
participant "CommServerWorker2"

create CommServer2
ChatExtension -> CommServer2 : getCommServer(port)

create Message
ChatExtension -> Message : new()
ChatExtension -> Message : writeMessage()

ChatExtension -> CommServer2 : addHandler(Message)

create CommServerWorker2
CommServer2 -> CommServerWorker2 : create()

@enduml
