@startuml lang04.2_analysis.png

actor User

participant "System" as s

User->s: Select the cell that he wants to insert a function
User->s: Select the wizard option
s->User: Display the avaliable functions and operators
User->s: Select the function or operators
s->User: Display a preview of the selected function/operator
User->s: Select the values he wants to use
User->s: Select the preview option
s->User: Show the result of the function with the selected values
User->s: Select the insert button
s->User: The result of the function is inserted in the selected cell
s->User: success

@enduml
