@startuml ipc01_03_analysis.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

title Multiple Sharing Analysis

actor User
participant "ShareCellsPanel" as Panel
participant "UIStartSharing" as UI


User --> Panel : Presses On/Off button

Panel --> UI : changeStatus()

Panel -> Panel : changesColorButtons()

User --> Panel : Users Lock Peers

Panel --> UI : lockPeers(onesSelected)

Panel --> UI : addSpreadsheetListener()

User --> Panel : Presses Share Cells button 

Panel --> UI : theOnesChosen(oneSelected)

UI -> UI : shareCells(oneSelected, theChosen)


@enduml
