/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr4.red.s3.ipc.n1140388.chatrooms.ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import lapr4.blue.s2.ipc.n1140956.ChatApplication.ChatUser;
import lapr4.blue.s2.ipc.n1140956.ChatApplication.ChatUsersStorage;
import lapr4.red.s3.ipc.n1140388.chatrooms.ChatRoom;
import lapr4.red.s3.ipc.n1140388.chatrooms.controller.ChatRoomController;

/**
 *
 * @author Alexandra Ferreira 1140388
 */
public class CreateChatRoomUI extends javax.swing.JFrame {

    /**
     * The chat room created
     */
    private ChatRoom room;

    /**
     * The list of invites
     */
    private List<ChatUser> invites;

    /**
     * The Login Participant Controller
     */
    private ChatRoomController controller;

    /**
     * Creates new form CreateChatRoomUI
     *
     * @param cntrl the chat room controller
     */
    public CreateChatRoomUI(ChatRoomController cntrl) {

        this.controller = cntrl;
        ChatUser activeParticipant = controller.owner();

        if (activeParticipant != null) {
            invites = new ArrayList<>();
            initComponents();

            ChatUsersStorage list = new ChatUsersStorage();

            for (ChatUser participants : list.getUserList().values()) {
                comboBoxInvites.addItem(participants);
            }

            this.btnPublic.setSelected(true);
            this.btnAddInvite.setVisible(false);
            this.lblInvites.setVisible(false);
            this.comboBoxInvites.setVisible(false);

            setResizable(false);
            setLocationRelativeTo(null);
            setVisible(true);

        } else {
            JOptionPane.showMessageDialog(CreateChatRoomUI.this, "You need to be logged in order to create a chat room!", "Not logged", JOptionPane.WARNING_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        btnPublic = new javax.swing.JRadioButton();
        btnPrivate = new javax.swing.JRadioButton();
        lblInvites = new javax.swing.JLabel();
        comboBoxInvites = new javax.swing.JComboBox();
        btnAddInvite = new javax.swing.JButton();
        btnCreateRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setText("Name: ");

        lblType.setText("Type:");

        btnPublic.setText("Public");
        btnPublic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicActionPerformed(evt);
            }
        });

        btnPrivate.setText("Private");
        btnPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrivateActionPerformed(evt);
            }
        });

        lblInvites.setText("Invites:");

        comboBoxInvites.setModel(new javax.swing.DefaultComboBoxModel());

        btnAddInvite.setText("Add Invite");
        btnAddInvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInviteActionPerformed(evt);
            }
        });

        btnCreateRoom.setText("Create Room");
        btnCreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(21, 21, 21)
                        .addComponent(txtName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblType)
                                .addGap(43, 43, 43)
                                .addComponent(btnPublic)
                                .addGap(59, 59, 59)
                                .addComponent(btnPrivate))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblInvites)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxInvites, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAddInvite)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCreateRoom)))))
                        .addGap(9, 9, 9)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(btnPublic)
                    .addComponent(btnPrivate))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInvites)
                    .addComponent(comboBoxInvites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddInvite)
                    .addComponent(btnCreateRoom))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicActionPerformed
        this.btnPrivate.setSelected(false);
        this.btnAddInvite.setVisible(false);
        this.lblInvites.setVisible(false);
        this.comboBoxInvites.setVisible(false);
    }//GEN-LAST:event_btnPublicActionPerformed

    private void btnPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrivateActionPerformed
        this.btnPublic.setSelected(false);
        this.btnAddInvite.setVisible(true);
        this.lblInvites.setVisible(true);
        this.comboBoxInvites.setVisible(true);
    }//GEN-LAST:event_btnPrivateActionPerformed

    private void btnAddInviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInviteActionPerformed
        if (comboBoxInvites.getSelectedItem() != null) {
            invites.add((ChatUser) comboBoxInvites.getSelectedItem());
            comboBoxInvites.removeItem(comboBoxInvites.getSelectedItem());
            JOptionPane.showMessageDialog(this, "Participant Added", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddInviteActionPerformed

    private void btnCreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRoomActionPerformed
        if (!this.txtName.getText().trim().isEmpty()) {
            if (this.btnPublic.isSelected()) {
                room = controller.createChatRoom(this.txtName.getText().trim(), 1, invites);
            } else if (this.btnPrivate.isSelected()) {
                room = controller.createChatRoom(this.txtName.getText().trim(), 2, invites);
            }

            if (room != null) {
                controller.startChat(room);
                JOptionPane.showMessageDialog(this, "You have succesfully created your Chat Room", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnCreateRoomActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInvite;
    private javax.swing.JButton btnCreateRoom;
    private javax.swing.JRadioButton btnPrivate;
    private javax.swing.JRadioButton btnPublic;
    private javax.swing.JComboBox comboBoxInvites;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInvites;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
