@startuml design_lang01.2.png

skinparam sequenceMessageAlign center

actor User
participant "Cell" as cell
participant "FormulaCompiler" as fc
participant "MonetaryExpressionCompiler" as mec
participant "CurrencyParser" as cp
participant "CurrencyEvalVisitor" as cev
participant "Formula" as form
participant "Expression" as exp


activate User
User->cell: setContent(String content)

activate cell
cell->cell: storeContent(content)


cell->fc: compile(Cell cell, String source)

activate fc
fc->mec: compile(Cell cell, String source)

activate mec
mec->cp: expression()

activate cp
cp-->mec: tree
deactivate cp
mec->cev: visit(tree)

alt
cev -> MoneyRate : calculateValue(currencyName, number, currency)
cev -> MoneyRate : calculateValueWithoutCurrency(currencyName, number)
end

activate cev
cev-->mec: expression
deactivate cev

mec-->fc: expression
deactivate mec

fc-->form: create(cell, expression)
activate form
deactivate form
fc-->cell: formula
deactivate fc

cell->cell: fireContentChanged()
cell->cell: reevaluate()

cell->form: evaluate()
activate form

form-->cell: value
deactivate form

deactivate cell

@enduml
