@startuml s1_ipc_findworkbook_design_01.png


class Extension {
}

class UIExtension {
}


class SearchWorkbookExtension {
  
 }

class UIExtensionSearchWorkbook {
  - NAME

 }

class SearchWorkbookPanel <<Observer>> {
  - controller
} 

class SearchWorkbookController {
    - fileContainer
    - thread
    + openWorkbook(File)
    + signalExit()
    + search(File rootDir, Observer ui)
 }

class FileContainer <<Observable>> <<synchronized>>{
  - lista
  + insertFile(FileDTO)
  + getFileDTO(int)
  + size()
  + emptyMe()
  + isToExit()
  + setToExit()
}

class FileDTO {
    - path
    - serialNumber
    - filename
    + FileDTO(File file, int serialNumber)
    + path()
    + filename()
    + serial()
    + toString()
}

class FilenameFilterBasic <<FilenameFilter>>{
+ FilenameFilterBasic()
}

interface FilenameFilter{
}

class FileFinder <<Runnable>>{
 + FileFinder(File , FileContainer, FilenameFilter)   
 + run()
 + searchInDir(File dir)
 - fileContainer
 - filenameFilter
 - root
}


FilenameFilter <|.. FilenameFilterBasic
FilenameFilterBasic <-- FileFinder
UIExtensionSearchWorkbook <-- SearchWorkbookExtension
SearchWorkbookPanel <-- UIExtensionSearchWorkbook
SearchWorkbookController <-- SearchWorkbookPanel
FileContainer <-- SearchWorkbookController
FileContainer o-- FileDTO
FileContainer <-- FileFinder
'FileDTO <-- SearchWorkbookUIExtension
FileDTO <-- SearchWorkbookPanel
'Event <.. Container

'SearchWorkbookUIExtension <.. Event
SearchWorkbookPanel <.. FileContainer :   EVENT FileDTO

UIExtension <|-- UIExtensionSearchWorkbook
Extension <|-- SearchWorkbookExtension


@enduml