@startuml
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

  actor User 
  participant "<<analysis>>\nSystem" as Sys
  User -> Sys : Makes a comment in a cell
  Sys -> User : Saves the user name and the comment made on the cell.
  User -> Sys : Places the mouse over a commented cell.
  Sys -> User : Shows who commented and the content of the comment, on the cell.

@enduml
