@startuml lang02.1_classDiagram.png

class ExcelExpressionCompiler {
    +compile(Cell cell, String source)
    +compile(Cell cell, Tree node)
}

interface Variable <extends Expression> {
    +Value applyTo(String name)
    +Value.Type getOperandValueType()
}

interface Expression 
interface BinaryOperator <extends Operator>
interface Operator

class TemporaryReference <implements Variable> {
    +applyTo(String name)
}

class AssignmentOperator <implements BinaryOperator> {
    +applyTo(Expression left, Expression right)
}

class TemporaryStorage {
    +exists(String left)
    +add(String left, Value right)
}


TemporaryReference --> Variable
Expression <|-- Variable

AssignmentOperator --> BinaryOperator
BinaryOperator --|> Operator
@enduml