@startuml core01_01_showSideBar.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

    title Show Extension Manager
    participant "uic : UIController" as UIC
    participant ExtensionManager as ExtM
    participant "extension : ManagerExtension" as EW
    participant "uiExtension : UIExtensionManager" as UIExt
    participant "ExtensionManagerPanel : JPanel" as cp

    UIC->ExtM:extensions.getextensions()
    loop for Extension ext : extensions
    UIC->EW : uiExtension = getUIextension(this)
    activate EW
    create UIExt
    EW->UIExt:new(extension,uic)
    deactivate EW
    UIExt->UIExt:getSideBar()
    activate UIExt
    create cp
    UIExt -> cp :  new (uic)
    deactivate UIExt 
    UIC->UIC : uiExtension.add(uiExtension);
    end
@enduml