@startuml core06.1_analysis.png

actor User

participant "System" as s

User->s: Select the image extension
s->User: The sidebar with the image features appears
User->s: Select the insert image option

loop the user wants to select more than 1 image
User->s: Finds the the image he wants to insert
s->User: The image appears in the sidebar with the URL/Link
end

alt the user wants to delete an image
User->s: Select the delete image option
s->User: A window appear with the URL/Links of the images
User->s: Selects the URL/Link of the image he wants to delete
end

s->User: success

@enduml
