@startuml uc_remove_event_design.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

title Use Case: Remove Event

actor "CRM User" as Actor  
participant RemoveEventUI as UI <<presentation>>
participant RemoveEventController as Controller <<application>>
participant "event:Event" as Domain <<domain>>
participant "contact:Contact" as DomainContact <<domain>>
database ContactRepository as Repository <<repository>>

Actor --> UI: Remove Event
activate UI

    UI -> Controller: create
    Controller -> Repository: getContactsList()
    Controller -> UI: contactsList
    UI -> Actor: contactsList
    Actor --> UI: Select a contact
    UI -> Controller: setContact(contact)


    Controller -> DomainContact: getEventsList(contact)
    Controller -> UI: eventsList
    UI -> Actor: eventsList
    Actor --> UI: Select a event
    UI -> Controller: setEvent(event)
    UI --> Actor: Display Event Info

    activate Controller
        Controller -> Repository: remove(event)
        Controller -> UI: Success
    deactivate Controller
    UI --> Actor: Success
deactivate UI

@enduml