@startuml  core01_2_03_design.png

class CleanSheets {
 }
class ExtensionManager << singleton >> {
    + listAllExtensionFound()
    + clear()
    + load(String classPath)
 }
abstract class Extension {
    + Extension(String name)
    + Extension(String name, int version, String desc)
 }

class DescriptionExtensionLoader {
    - allExtensions
    - defaultLoadList;
    - userFinishedSelection
    - defaultListBuilder
    + buildDefaultLoadList()
    + retrieveAllExtensions()
    + contactUser()
    + validateLoadingListOfUniqueExtensions()
    + loadList()
    + isUserFinishedSelection()
    + indicateUserFinishedSelection()
    + waitSignal()
    + wakeAll()
 }

class DescriptionExtensionLoaderUI {
    - controller
 }

class DescriptionExtensionLoaderController {
  - DescriptionExtensionLoader
    + validateLoadingList()
    + loadList()
    + indicateUserFinishedSelection()
 }

interface Metadatable {
    + metadata()
    + getName()
    + version()
    + description()
}

class Metadata << (C,orchid)  immutable >>{
 - Name
 - Version
 - Description
 + getName()
 + version()
 + description()
}

class Name << (C,orchid)  immutable >>{
 - name
 + name();
}
class Version << (C,orchid)  immutable >>{
 - version
 + version()
}
class Description << (C,orchid)  immutable >>{
 - description
 + description()
}
class MetadataFactory << singleton >>{
 + instance()
 + buildMetadata(String name)
 + buildMetadata (String name, int version, String desc)
 + buildExtensionDTO(Metadatable extension)
}

class ExtensionDTO << (C,orchid)  immutable >>{
  - Metadata
  - String classname
  + metadata()
  + getName()
  + version()
  + description()
  + toString()
  + classname()
}

interface DefaultExtensionLoadListBuilder{
    + buildDefaultLoadList(List<ExtensionDTO> allExtensions)
} 

class DefaultExtensionLoadListBuilderByLatestVersion{
    + buildDefaultLoadList(List<ExtensionDTO> allExtensions)
}

'DescriptionExtensionLoader
'DescriptionExtensionLoaderUI
'DescriptionExtensionLoaderController
'Metadata
'Name
'Version
'Description
'MetadataFactory
'ExtensionDTO
'CleanSheets
'ExtensionManager


DescriptionExtensionLoaderController --> DescriptionExtensionLoader
DescriptionExtensionLoaderUI --> DescriptionExtensionLoaderController
DescriptionExtensionLoader --> ExtensionManager
ExtensionManager o-- Extension

DescriptionExtensionLoader --> Extension
DescriptionExtensionLoader --> ExtensionDTO
DescriptionExtensionLoader --> Metadata

DescriptionExtensionLoaderUI --> ExtensionDTO
DescriptionExtensionLoaderController --> ExtensionDTO

CleanSheets --> ExtensionManager

Metadata --> Name
Metadata --> Version
Metadata --> Description

MetadataFactory --> Metadata
MetadataFactory --> ExtensionDTO

ExtensionDTO --> Metadata

Extension ..|> Metadatable
ExtensionDTO ..|> Metadatable
Metadata ..|> Metadatable

CleanSheets --> DescriptionExtensionLoader


DescriptionExtensionLoader --> DefaultExtensionLoadListBuilder
DefaultExtensionLoadListBuilder <|.. DefaultExtensionLoadListBuilderByLatestVersion
'DefaultExtensionLoadListBuilder <-- DescriptionExtensionLoader

'DescriptionExtensionLoader --> MetadataFactory
'Extension --> MetadataFactory


@enduml