@startuml image03.png

class Workbook {
  - ArrayStorage
    + retrieveArrayStorage()
 }

class ArrayStorage {
  - Map<String , ArrayItem> arrayMap
  + retrieveArrayItem(String name)
 }
class ArrayItem {
  - name
  - value
+ ArrayItem(String name)
+ ArrayItem(String name, Value value)
+ getName() 
+ getValue() 
+ setValue(Value value)
+ evaluate()
 }
class ArrayItemDTO  << immutable >>{
  - name
  - value
 }

class AssignmentOperator {
 + applyTo()
}
class FormulaEvalVisitor {
 + visitVariable()
}

class Cell {
 + getSpreadsheet()
}

class Spreadsheet {
  +  getWorkbook()
}

class Value {
 }

interface Variable <<sprint 1>>{
+ applyTo()
+ getOperandValueType()
 }
interface Expression {
 }



class VariableEditorController {
 }

class VariableEditorController {
    + retriveActiveWorkbookVariableList()
 }
class VariableEditorExtension {
 }
class VariableEditorPanel <<Observer>>{
 }
class UIExtensionVariableEditor {
 }
class VariableEditorWatchdog  <<Singleton>><<Observable>>{
    + signalChange()
 }

class UiController{
 - activeWorkbook
 + getActiveWorkbook()
}

'Workbook
'ArrayStorage
'ArrayItem
'Variable
'Value
'VariableEditorExtension
'VariableEditorController
'VariableEditorPanel
'UIExtensionVariableEditor

Workbook --> ArrayStorage
ArrayStorage o-- ArrayItem
ArrayItem ..|> Variable
Variable ..|> Expression
AssignmentOperator --> Expression
AssignmentOperator --> ArrayItem
FormulaEvalVisitor --> Cell
Cell --> Spreadsheet
Spreadsheet --> Workbook
FormulaEvalVisitor --> ArrayItem
UiController --> Workbook

ArrayItem --> Value
ArrayItem --> ArrayItemDTO

ArrayItem --> VariableEditorWatchdog



VariableEditorController --> UiController
VariableEditorController --> ArrayStorage

'VariableEditorController --> UIExtensionVariableEditor

VariableEditorExtension --> UIExtensionVariableEditor
UIExtensionVariableEditor --> VariableEditorPanel
VariableEditorPanel --> VariableEditorController

VariableEditorWatchdog --> VariableEditorPanel

VariableEditorPanel --> ArrayItemDTO



@enduml