/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr4.blue.s1.lang.n1140948.functionwizard;

import csheets.core.IllegalValueTypeException;
import csheets.core.formula.Formula;
import csheets.core.formula.Function;
import csheets.core.formula.FunctionParameter;
import csheets.core.formula.compiler.FormulaCompilationException;
import csheets.ui.ctrl.UIController;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago Silvestre
 */
public class FunctionWizardGUI extends javax.swing.JFrame {

    private final AddFunctionController m_controller;
    private final UIController uiController;
    private final DefaultListModel<String> lstFuncString;
    private final DefaultListModel<Function> lstFunc;

    /**
     * Creates new FunctionWizardGUI
     * @param uiController The UI Controller
     */
    public FunctionWizardGUI(UIController uiController) {
        initComponents();
        this.uiController = uiController;
        m_controller = new AddFunctionController();
        this.lstFunc = new DefaultListModel<>();
        this.lstFuncString = new DefaultListModel<>();

        pack();
        setLocationRelativeTo(null);
        this.setVisible(true);

        addFunctionstoList();
        this.jFunctionsList.setModel(lstFuncString);
        this.jFunctionlbl.setText("Select a Function");
    }

    /**
     * Method that adds the list of functions to JList.
     */
    private void addFunctionstoList() {
        for (Function function : this.m_controller.listFunctions()) {
            this.lstFunc.addElement(function);
            this.lstFuncString.addElement(function.getIdentifier());
        }
    }

    /**
     * This method is called from within the constructor to initialize the syntax.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFunctionListPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jFunctionsList = new javax.swing.JList<>();
        jHelpPanel = new javax.swing.JPanel();
        jFunctionlbl = new javax.swing.JLabel();
        jHelplbl = new javax.swing.JLabel();
        jHelptxt = new javax.swing.JTextField();
        jButtonPanel = new javax.swing.JPanel();
        jCancelButton = new javax.swing.JButton();
        jApplyButton = new javax.swing.JButton();
        jSelectFunctionlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Function Wizard");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jFunctionsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jFunctionsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jFunctionsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jFunctionsList);

        javax.swing.GroupLayout jFunctionListPanelLayout = new javax.swing.GroupLayout(jFunctionListPanel);
        jFunctionListPanel.setLayout(jFunctionListPanelLayout);
        jFunctionListPanelLayout.setHorizontalGroup(
            jFunctionListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFunctionListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jFunctionListPanelLayout.setVerticalGroup(
            jFunctionListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFunctionListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        jHelplbl.setText("Help:");

        jHelptxt.setEnabled(false);

        javax.swing.GroupLayout jHelpPanelLayout = new javax.swing.GroupLayout(jHelpPanel);
        jHelpPanel.setLayout(jHelpPanelLayout);
        jHelpPanelLayout.setHorizontalGroup(
            jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addGroup(jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFunctionlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jHelpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jHelplbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jHelptxt)))
                .addContainerGap())
        );
        jHelpPanelLayout.setVerticalGroup(
            jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addComponent(jFunctionlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHelplbl)
                    .addComponent(jHelptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jButtonPanel.setPreferredSize(new java.awt.Dimension(380, 380));

        jCancelButton.setText("Cancel");
        jCancelButton.setMaximumSize(new java.awt.Dimension(70, 25));
        jCancelButton.setMinimumSize(new java.awt.Dimension(70, 25));
        jCancelButton.setPreferredSize(new java.awt.Dimension(70, 25));
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jApplyButton.setText("Apply");
        jApplyButton.setMaximumSize(new java.awt.Dimension(70, 25));
        jApplyButton.setMinimumSize(new java.awt.Dimension(70, 25));
        jApplyButton.setPreferredSize(new java.awt.Dimension(70, 25));
        jApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApplyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jButtonPanelLayout = new javax.swing.GroupLayout(jButtonPanel);
        jButtonPanel.setLayout(jButtonPanelLayout);
        jButtonPanelLayout.setHorizontalGroup(
            jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonPanelLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jApplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jButtonPanelLayout.setVerticalGroup(
            jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jApplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSelectFunctionlbl.setText("Select a function:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFunctionListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSelectFunctionlbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jHelpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSelectFunctionlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFunctionListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHelpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApplyButtonActionPerformed
        try {
            String syntax = this.jFunctionlbl.getText();
            uiController.getActiveCell().setContent(syntax);
            dispose();
        } catch (FormulaCompilationException a) {
            JOptionPane.showMessageDialog(this, a.getMessage());
        }
    }//GEN-LAST:event_jApplyButtonActionPerformed

    private void jFunctionsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jFunctionsListValueChanged
        int index = this.jFunctionsList.getSelectedIndex();

        if (index < this.lstFunc.size()) {
            Function func = this.lstFunc.getElementAt(index);
            this.jFunctionlbl.setText(buildSyntax(func, func.getPARAMETERS()));
        }
    }//GEN-LAST:event_jFunctionsListValueChanged

    /**
     * Method thats build a description a function with parameters.
     *
     * @param func
     * @param param
     * @return syntax String
     */
    public String buildSyntax(Function func, FunctionParameter param[]) {
        String auxHelp = "";
        StringBuilder builder = new StringBuilder();
        int numParam = param.length;
        if (numParam > 0) {
            if (!this.jFunctionsList.getValueIsAdjusting()) {
                builder.append("=");
                builder.append(func.getIdentifier());
                builder.append("(");
                for (int i = 0; i < numParam; i++) {
                    if (i > 0) {
                        builder.append(";");
                    }
                    builder.append(param[i].getValueType().toString());
                }
                builder.append(")");
                return builder.toString();
            }
        } else{
            builder.append("=");
            this.jFunctionlbl.setText(func.getIdentifier());
            builder.append("(NUMBER)");
            return builder.toString();
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jApplyButton;
    private javax.swing.JPanel jButtonPanel;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JPanel jFunctionListPanel;
    private javax.swing.JLabel jFunctionlbl;
    private javax.swing.JList<String> jFunctionsList;
    private javax.swing.JPanel jHelpPanel;
    private javax.swing.JLabel jHelplbl;
    private javax.swing.JTextField jHelptxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSelectFunctionlbl;
    // End of variables declaration//GEN-END:variables
}
