@startuml lang04.1_classDiagram.png

    skinparam monochrome true
    hide methods

    title Class Diagram

    class FunctionWizardGUI << (C, white) >>{
    }

    class AddFunctionController << (C, white) >>{
    }

    class UIController << (C, lightgray) >>{
    }

    interface Function << (I, lightgray) >>{
    }

    class Language << (C, lightgray) >>{
        unaryOperators
        binaryOperators
        functions
    }

    class FunctionCall << (C, lightgray) >>{
    }

    FunctionCall -up-> Function : getParameters()

    Language -up-> FunctionCall : getFunctions()

    AddFunctionController -left-> Language : getFunctions()

    FunctionWizardGUI -down-> AddFunctionController: getFunctions()

    FunctionWizardGUI -up-> UIController: getActiveCell()

@enduml
