@startuml
    participant "CommServer2"
    participant "ServerSocket"
    participant "CommWorker"
    participant "aSocket:Socket" as aSocket

create ServerSocket
  CommServer2 -> ServerSocket : new();
  CommServer2 -> ServerSocket : aSocket=accept();


@enduml
