/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr4.blue.s2.ipc.n1140948.advancedworkbooksearch.UI;

import csheets.core.Cell;
import csheets.ui.ctrl.UIController;
import javax.swing.table.DefaultTableModel;
import lapr4.blue.s2.ipc.n1140948.advancedworkbooksearch.DescodificadorWorkbook;
import lapr4.blue.s2.ipc.n1140948.advancedworkbooksearch.controller.PreviewWorkbookController;
import lapr4.green.s1.ipc.n1970581.findworkbook.controller.SearchWorkbookController;
import lapr4.green.s1.ipc.n1970581.findworkbook.ui.SearchWorkbookPanel;

/**
 *
 * @author Tiago Silvestre
 */
public class PreviewUI extends javax.swing.JFrame {
    
    private final DescodificadorWorkbook descWorkbook;
    private final SearchWorkbookPanel searchWorkbookPanel;
    private final SearchWorkbookController searchWorkbookController;
    private final PreviewWorkbookController previewController;
    private final UIController uiController;
    private final Cell cellList[][][];
    private int paginaAtual = 0;
    private String[] matrixLine;
    private Object[][] matrixColumn;
    
    private static int[] listNum;
    private static final String[] listAbc = {"A", "B", "C", "D", "E", "F", "G",
        "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "X", "Y",
        "Z", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN",
        "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AX", "AY", "AZ"};

    /**
     * Creates new form PreviewUI
     * @param descodificador
     * @param uiController
     */
    public PreviewUI(DescodificadorWorkbook descodificador, UIController uiController) {         
        initComponents();
        this.uiController = uiController;
        this.descWorkbook = descodificador;
        this.cellList = descWorkbook.CellList();
        this.searchWorkbookPanel = new SearchWorkbookPanel(uiController);
        this.searchWorkbookController = new SearchWorkbookController(uiController);
        this.previewController = new PreviewWorkbookController(searchWorkbookPanel, uiController);
        this.listNum = createListaNumeros();
        this.WorkbookNamelbl.setText(descWorkbook.File().filename());
        this.SheetNumberlbl.setText(""+(paginaAtual+1));        
        
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        showPage();
        jTable.setFillsViewportHeight(true);
        this.LeftSheetButton.setEnabled(false);
        descWorkbook.descodificador(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelsPanel = new javax.swing.JPanel();
        Workbooklbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        WorkbookNamelbl = new javax.swing.JLabel();
        SheetNumberlbl = new javax.swing.JLabel();
        GridPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        ButtonPanel = new javax.swing.JPanel();
        CloseButton = new javax.swing.JButton();
        OpenWorkbookButton = new javax.swing.JButton();
        RightSheetButton = new javax.swing.JButton();
        LeftSheetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Workbook Preview");
        setAlwaysOnTop(true);
        setResizable(false);

        Workbooklbl.setText("Workbook:");

        jLabel2.setText("Sheet:");

        javax.swing.GroupLayout LabelsPanelLayout = new javax.swing.GroupLayout(LabelsPanel);
        LabelsPanel.setLayout(LabelsPanelLayout);
        LabelsPanelLayout.setHorizontalGroup(
            LabelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Workbooklbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorkbookNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SheetNumberlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );
        LabelsPanelLayout.setVerticalGroup(
            LabelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LabelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WorkbookNamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LabelsPanelLayout.createSequentialGroup()
                        .addComponent(Workbooklbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LabelsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(LabelsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SheetNumberlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout GridPanelLayout = new javax.swing.GroupLayout(GridPanel);
        GridPanel.setLayout(GridPanelLayout);
        GridPanelLayout.setHorizontalGroup(
            GridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GridPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
        GridPanelLayout.setVerticalGroup(
            GridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GridPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        OpenWorkbookButton.setText("Open");
        OpenWorkbookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenWorkbookButtonActionPerformed(evt);
            }
        });

        RightSheetButton.setText(">");
        RightSheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightSheetButtonActionPerformed(evt);
            }
        });

        LeftSheetButton.setText("<");
        LeftSheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftSheetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeftSheetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RightSheetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(OpenWorkbookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseButton)
                    .addComponent(OpenWorkbookButton)
                    .addComponent(RightSheetButton)
                    .addComponent(LeftSheetButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GridPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GridPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        uiController.setActiveWorkbook(previewController.getPreviousWorkbook());
        dispose();
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void OpenWorkbookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenWorkbookButtonActionPerformed
        dispose();
    }//GEN-LAST:event_OpenWorkbookButtonActionPerformed

    private void RightSheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightSheetButtonActionPerformed
        nextPage();
    }//GEN-LAST:event_RightSheetButtonActionPerformed

    private void LeftSheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftSheetButtonActionPerformed
        pagePrevious();
    }//GEN-LAST:event_LeftSheetButtonActionPerformed

    private void nextPage() {
        LeftSheetButton.setEnabled(true);
        paginaAtual++;
        SheetNumberlbl.setText(""+ (paginaAtual + 1));
        showPage();
        if (paginaAtual == descWorkbook.numSheet() - 1) {
            RightSheetButton.setEnabled(false);
        }
    }
    
    private void pagePrevious() {        
        RightSheetButton.setEnabled(true);
        paginaAtual--;
        SheetNumberlbl.setText(""+ (paginaAtual + 1));
        showPage();      
        if (paginaAtual == 0) {
            LeftSheetButton.setEnabled(false);
        }
    }
    
    private void showPage() {
        preencheValoresMatrix();
        jTable.setModel(new DefaultTableModel(matrixColumn, matrixLine));
    }    
    
    /**
     * Import cells and do new sheet to show
     * @return
     */
    private void preencheValoresMatrix() {

        this.matrixColumn = importColumn();
        this.matrixLine = importLine();

        int max = descWorkbook.matrixSize();

        try {
            for (int i = 0; i < max; i++) {
                for (int j = 0; j < max; j++) {
                    matrixColumn[j][i + 1] = cellList[j][i][paginaAtual].getContent();
                }
            }
        } catch (NullPointerException e) {
            
        }

    }
    
    private Object[][] importColumn() {
        int min = descWorkbook.minCellHorizontal()[paginaAtual];
        Object[][] data = new Object[5][6];
        
        if((min+5)>listNum.length){
            int r =(min+5)-listNum.length;
            min=min-r;
        }
        
        for (int i = 0; i < 5; i++) {
            data[i][0] = listNum[i + min];
        }
        return data;
    }
    
    private String[] importLine() {
        int min = descWorkbook.minCellVertical()[paginaAtual];
        
        if((min+5)>listAbc.length){
            int r =(min+5)-listAbc.length;
            min=min-r;
        }
        
        String[] columnNames = new String[6];
        columnNames[0] = "";

        for (int i = 1; i < 6; i++) {
            columnNames[i] = listAbc[i - 1 + min];
        }

        return columnNames;
    }
    
    private int[] createListaNumeros() {
        int[] list = new int[128];
        for (int i = 0; i < 128; i++) {
            list[i] = i + 1;
        }
        return list;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton CloseButton;
    private javax.swing.JPanel GridPanel;
    private javax.swing.JPanel LabelsPanel;
    private javax.swing.JButton LeftSheetButton;
    private javax.swing.JButton OpenWorkbookButton;
    private javax.swing.JButton RightSheetButton;
    private javax.swing.JLabel SheetNumberlbl;
    private javax.swing.JLabel WorkbookNamelbl;
    private javax.swing.JLabel Workbooklbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
