@startuml ipc02_03_design.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

title Multiple Realtime Workbook Search Design

actor User

participant "SearchWorkbokPanel" as searchWorkbookPanel
participant "RealTimeSearchUI" as realTimeUI
participant "RealTimeSearch" as realTime

User --> searchWorkbookPanel : realtime search

searchWorkbookPanel --> realTimeUI : create(Frame frame, boolean modal,SearchWorkbookController controller, JList list, ArrayList<JButton> bts )

opt add Folders
realTimeUI --> User : open File Chooser
User --> realTimeUI : select folder
realTimeUI --> realTimeUI : model.addElement(String path)

end opt

opt delete Folders
realTimeUI --> User : select folder to delete
realTimeUI --> realTimeUI : model.remove(String path)

end opt

User --> realTimeUI : search
realTimeUI --> realTime : create(SearchWorkbookController controller, ArrayList<String> list, JList jList)
note right: Different Threads will realize\n the search of workbooks in folders.\n These folders will be permanently covered\n in order to find new instances of Workbooks.

loop for(String str : list )
realTime --> realTime ::findWorkbook(str)
note right : This method will call itself recursivly\n while the path have childs.


alt
	realTime --> searchWorkbookPanel : addToListWindow(File root)
end alt
end loop


@enduml
