@startuml ipc04_2_cd.png
  class ImportAction

  class ExportLinkAction
   
  class ImportExportMenu
  class ExtensionImportExport {
    -String NAME;
  }

  class UIController
  class ImportLinkUI{
   -UIController uiController;
  }

  class UIExtensionImportExport

  class JMenuItem

  class ExportLinkUI{
    -Cell[][] selectedCells;
    -UIController uiController;
  }

  class ImportExportTextLinkController{
    +checkCells(this.textSpecialChar.getText(), selectedCells);
    +importFromTextFile(String filename, String specialChar, boolean containsHeader);
    +exportToTextFile(selectedCells, fileChooser.getSelectedFile().getAbsolutePath(), this.textSpecialChar.getText());
  }

  ExtensionImportExport -> UIExtensionImportExport : getUIExtension(UIController)
  UIExtensionImportExport -> ImportExportMenu : getMenu()
  ImportExportMenu -> JMenuItem : 'items'
  JMenuItem o-> ImportLinkAction : action
  ImportAction -> ImportLinkUI
  UIController -> ImportExportTextLinkController
  ImportLinkUI -> ImportExportTextLinkController
  JMenuItem o-> ExportLinkAction : action
  ExportAction -> ExportLinkUI
  ExportLinkUI -> ImportExportTextLinkController
@enduml
