@startuml ipc04.2_analysis.png

actor User

participant "System" as s

User->s: Selects a range of cells to be used as source or destination for the operation

User->s: Selects the import/export text extension

alt the user had selected the import data from a text file option
s-->User: asks for the file to import the data from
User->s: finds the location of the text file he wants to import
s->User: updates the cells selected by the user with the data from the imported text file
end

alt the user had selected the export data to a text file option
s-->User: asks for the file name and location to export the data to
User->s: choose a location and writes the name of the exported text file
User->s: configures a special character to separate columns
s-->User: creates the text file with the data on the cells selected by the user
end

s-->User: success

@enduml
